### ISSUE TITLE
Decoding TAP3

### ISSUE THREAD

**Issue by saramirabi** [Olernov/TAP3.Loader#1]
Hi,
Is it possible to decode tap files with this library?

**Comment by Olernov** [comment]
It is possible but will require some adoption since this module is developed for particular database structure. And some pre-compiled ASN structures are missing here but I think I can upload them. Do you really need to decode the GSM TAP3 files used for roaming charges interchange?

**Comment by saramirabi** [comment]
Yes i must decode them all. for retreiving our needfull data. 
Would you mind please give me a small step by step guidance in this regard?

BR,
Sara

**Comment by Olernov** [comment]
Check this repo: https://github.com/Olernov/TAP3. It has all necessary files and you can compile it using Visual Studio 2013 or higher. If you just want to decode some TAP files and view their contents you can use online decoder https://www.marben-products.com/decoder-asn1-cdr/. But if you are planning to implement full Transfer Account Procedure (TAP) then it's anyway a complex task involving your billing system vendor. You can contact me at olernov@gmail.com if you have any questions regrading this.
